sudo: required

notifications:
  email: 
    on_success: never
    on_failure: always

language: bash

services:
- docker

env:
  global:
    - ROOT=/opt/rootfs
    - JOBS=2
  matrix:
    - TAG=wheezy-64    CMD=run_tests

script:
- .travis/docker_run.sh

